### ISSUE TITLE
GHC 9.12.1 sub-word division

### ISSUE THREAD

**Issue by hasufell** [haskell/security-advisories#265]
Mandatory information:

* Package : GHC
* cvss: `?`
* affected versions: 9.12.1 only

Optional:

* cve: `?`
* keywords: `?`
* aliases: `?`
* related: `?`
* affected OSes: `?`
* affected architecture: `?`
* declarations: `?`
* Long description: `?`

----

References:

* https://discourse.haskell.org/t/psa-correctness-issue-in-ghc-9-12/11204
* https://gitlab.haskell.org/ghc/ghc/-/issues/25653

**Comment by TristanCacqueray** [comment]
Thank you @hasufell for the heads up. Perhaps we can also use [CWE-1335](https://cwe.mitre.org/data/definitions/1335.html): Incorrect Bitwise Shift of Integer, since that seems to be the root cause of the issue, though the bug doesn't exactly match the description.

It would be good to know if the other backends are affected, or if this is only happening on x86.

Here is a tentative draft:

```toml
[advisory]
id = "HSEC-2025-0000"
cwe = [682]
keywords = ["integrity", "dos"]

[[affected]]
ghc-component = "ghc"
cvss = "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:H/A:H"

[[affected.versions]]
introduced = "9.12.1"
fixed = "9.12.2"

[[references]]
type = "REPORT"
url = "https://gitlab.haskell.org/ghc/ghc/-/issues/25653"

[[references]]
type = "REPORT"
url = "https://discourse.haskell.org/t/psa-correctness-issue-in-ghc-9-12/11204"

[[references]]
type = "FIX"
url = "https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13820"
```

# Subword division operations may produce incorrect results

Arithmetic operations may produce incorrect results on the native x86 backend when compiled with optimizations.
For the most part, this bug only causes availability and data integrity issues.
However, in some circumstances, it may result in other, more complicated security related flaws, such as buffer overflow conditions.
